name: weather_repository
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.8.1

dependencies:
  equatable: ^2.0.0
  json_annotation: ^4.6.0
  open_meteo_api:
    path: ../open_meteo_api

dev_dependencies:
  build_runner: ^2.0.0
  coverage: ^1.0.3
  json_serializable: ^6.3.1
  mocktail: ^1.0.0
  test: ^1.16.4